version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app # 인스턴스에서 파일이 저장될 위치
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root